version: "3.7"
services:
 web-server:
  image: jamesattree/php_apache:latest
  restart: always
  volumes:
   - "/var/www2/html/:/var/www/html/"
   - "/etc/letsencrypt/:/etc/letsencrypt/"
   - apache_conf:/etc/apache2
  ports:
   - "80:80"
   - "443:443"

 mysql-server:
  image: mysql:8.0.19
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes:
   - mysql-data:/var/lib/mysql
  ports:
   - 3306:3306

 phpmyadmin:
  image: jamesattree/phpmyadminssl
  restart: always
  volumes:
   - phpmyadmin_apache_conf:/etc/apache2
   - "/etc/letsencrypt/:/etc/letsencrypt/"
  environment:
   PMA_HOST: mysql-server
  ports:
   - "5000:80"
   - "8443:443"

volumes:
 mysql-data:
 apache_conf:
 phpmyadmin_apache_conf:
